---
spring:
  profiles: common
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.37.1:3306/microservice?useSSL=false
    username: root
    password: 1q2w3e4r
  redis:
    url: redis://192.168.37.1:6379
    database: 0
  rabbitmq:
    host: 192.168.37.101
    port: 5672
    username: spring
    password: spring
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    preferIpAddress: true
    ipAddress: 192.168.37.1
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://192.168.37.101:8701/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS