server:
  port: 8702

eureka:
  instance:
    preferIpAddress: true
    ipAddress: 192.168.37.101
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://192.168.37.101:8701/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  file: gateway.log
